openapi: 3.0.0

servers:
  - url: https://yfkavlkdo6.execute-api.us-east-1.amazonaws.com/dev/api

info:
    version: 0.1.0 
    title: CODATA Fundamental Physical Constants
    description: A simple API to retrieve information about CODATA Fundamental Physical Constants

paths:
    /search:
        get:
            summary: search for constants
            description: Returns an object with search results statistics and information on constants mathing search criteria
            operationId: searchConstants
            parameters:
                - name: name
                  in: query
                  description: Search by name. This parameter is a regular expression macth on the english name of the latest version
                  schema:
                      type: string
                - name: page
                  in: query
                  description: The search page results to display
                  schema:
                      type: integer
                - name: perPage
                  in: query
                  description: The number of matches to display per search result page
                  schema:
                      type: integer
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    filter:
                                        type: object
                                        description: values used as search filter
                                    found:
                                        type: integer
                                        description: the number of constant found
                                    page:
                                        type: integer
                                        description: the current page
                                    perPages:
                                        type: integer
                                        description: the number of matches to return per page
                                    nPages:
                                        type: integer
                                        description: the total number of pages for this search
                                    matches:
                                        type: array
                                        description: the matching constants for this page
                                        items:
                                            $ref: '#/components/schemas/ConstantInstance'

    /ConstantDefinition/{id}:
        get:
            description: Returns a Constant Definition
            operationId: getConstantDefinition
            parameters:
                - in: path
                  name: id
                  schema:
                    type: string
                  required: true
                  description: the resource identifier
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ConstantInstance'
    /ConstantInstance/{id}:
        get:
            description: Returns a Constant Instance
            operationId: getConstantInstance
            parameters:
                - in: path
                  name: id
                  schema:
                    type: string
                  required: true
                  description: the resource identifier
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ConstantInstance'

security:
  - api_key : []

components:
    securitySchemes:
        api_key:
            type: apiKey
            name: key
            in: query
    schemas:
        ConstantDefinition:
            allOf:
              - $ref: '#/components/schemas/Resource'
              - type: object
                properties:
                    instances:
                        type: array
                        items: 
                            $ref: '#/components/schemas/ConstantInstance'
        ConstantInstance:
            allOf:
              - $ref: '#/components/schemas/Resource'
              - type: object
                properties:
                    units:
                        type: object
                        description: The units for this constant expressed in various formats
                        properties:
                            SI:
                                type: string
                                description: The units for this constant as expressed in the International System of Units (SI) coding system
                            UCUM:
                                type: string
                                description: The units for this constant as expressed in the Unified Code for Units of Measure (UCUM) coding system
                            UOM:
                                type: string
                                description: The units for this constant as a Unit-of-measurement project URL. JSON-LD and Turtle versions of the units can be retrieved by adding a .json or .ttl suffix to this value.
                    versions:
                        type: array
                        description: The values for this constant across all versions
                        items:
                            $ref: '#/components/schemas/ConstantValue'
        ConstantValue:
            allOf:
              - $ref: '#/components/schemas/Resource'
              - type: object
                properties:
                    version:
                        type: string
                        description: The version this value belongs to.
                    value:
                        type: string
                        description: The constant value expressed as a string. This is expressed as a string to preserve display format and floating point accuracy.
                    uncertainty:
                        type: string
                        description: The constant standard uncertainty. This is expressed as a string to preserve display format and floating point accuracy.
        Resource:
            type: object
            properties:
                type:
                    type: string
                    description: The resource type.
                id:
                    type: string
                    description: The resource indentifier.
                ids:
                    type: object
                    description: A colleciton of additional external identifiers for the resource.
                name:
                    type: string
                    description: The resource name in English
            required:
                - type
                - id
            

